@startmindmap
+ Backend
+ Frontend
+ Admin
+ General
++ Docker
+++_ Obraz
+++_ Kontener
+++_ Service
+++_ Sieć
+++_ Volumen
+++_ Secret
+++_ Docker-compose
+++_ Dockerfile
+++_ Profile
+++_ Porty
@endmindmap
